version: '3'

services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_API_PATH=http://0.0.0.0:9000
        - REACT_APP_ENV=Production
    ports:
      - 1234:1234

  frontend-staging:
    build:
      context: .
      args:
        - REACT_APP_API_PATH=http://0.0.0.0:9001
        - REACT_APP_ENV=Staging
    ports:
      - 1235:1234
