version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2-jessie
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
        command: |
          yarn
          yarn test
      - save_cache:
          key: v1-{{ checksum "yarn.lock" }}
          paths:
            "node_modules"
