version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0-jessie
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          command: |
            yarn
            yarn test
      - save_cache:
          key: v1-{{ checksum "yarn.lock" }}
          paths:
            "node_modules"
